# NumPy Tutorial

https://www.w3schools.com/python/numpy/

## Searching Arrays

Searching an array can be done with `np.where(array == <condition>)`

The result is a tuple indicating the name of the array and the index/indices where the value is found.

Note that one can do matrix math on the array before applying the boolean logic. For example, to find all even values, use `array % 2 == 0` to first apply the modulo to the entire array.

In [34]:
import numpy as np
from configurations import printer, logger

array = np.array([*range(1, 6), *range(2, 7)])

printer('Array is:\n%s', array)
printer('1 is found at index/indices:\n%s', np.where(array == 1))
printer('2 is found at index/indices:\n%s', np.where(array == 2))
array_modulo_2 = array % 2
printer('Array modulo 2 is:\n%s', array_modulo_2)
printer('Array modulo 2 is 0 at indices:\n%s', np.where(array_modulo_2 == 0))

printer('Array is odd at indices:\n%s', np.where(array % 2 == 1))

logger.warning(r'Note that printing % symbol in logs can be problematic')

Array is:
[1 2 3 4 5 2 3 4 5 6]
1 is found at index/indices:
(array([0]),)
2 is found at index/indices:
(array([1, 5]),)
Array modulo 2 is:
[1 0 1 0 1 0 1 0 1 0]
Array modulo 2 is 0:
(array([1, 3, 5, 7, 9]),)
Array is odd:
(array([0, 2, 4, 6, 8]),)

2023-08-01 07:46:50 
	Logger: numpy-tutorial Module: 2144433392 Function: <module> File: 2144433392.py Line: 15
Note that printing % symbol in logs can be problematic



### Search Sorted

You can search for the indices where a new value would be inserted into a sorted array with `np.searchsorted()`.

In [38]:
import numpy as np
from configurations import printer, logger

unsorted_array = np.array([3, 1, 5])
sorted_array = np.sort(array)

printer(
    '2 would go into the sorted array at:\n%s',
    np.searchsorted(sorted_array, 2)
    )

printer(
    '2 would go into the unsorted array at:\n%s',
    np.searchsorted(unsorted_array, 2)
    )

logger.warning(
    'Note that `np.searchsorted()` will return values even if the array is\n'
    'not sorted! In other words, it presumes your array is already sorted,\n'
    'and if it is not, it will instead return the first index where the value\n'
    'is greater than the previous index.'
)

printer(
    '4 would go into the sorted array at:\n%s',
    np.searchsorted(sorted_array, 4)
    )

printer(
    '4 would go into the unsorted array at:\n%s',
    np.searchsorted(unsorted_array, 4)
    )

2 would go into the sorted array at:
1
2 would go into the unsorted array at:
2
4 would go into the sorted array at:
5
4 would go into the unsorted array at:
2


#### Search From the Right Side

Use the argument `side='right'` to instead search from the right side of the array.

In [39]:
import numpy as np
from configurations import printer

unsorted_array = np.array([3, 1, 5])
sorted_array = np.sort(array)

printer(
    '2 would go into the sorted array at index counting from the right:\n%s',
    np.searchsorted(sorted_array, 2, side='right')
    )

printer(
    '2 would go into the unsorted array  at index counting from the right:\n%s',
    np.searchsorted(unsorted_array, 2, side='right')
    )

printer(
    '4 would go into the sorted array  at index counting from the right:\n%s',
    np.searchsorted(sorted_array, 4, side='right')
    )

printer(
    '4 would go into the unsorted array  at index counting from the right:\n%s',
    np.searchsorted(unsorted_array, 4, side='right')
    )

2 would go into the sorted array at index counting from the right:
3
2 would go into the unsorted array  at index counting from the right:
2
4 would go into the sorted array  at index counting from the right:
7
4 would go into the unsorted array  at index counting from the right:
2


### Multiple Values

To search for multiple values, pass them as their own array.

In [40]:
import numpy as np
from configurations import printer

array = np.array([1, 3, 5, 7])
insert_array = np.array([2, 4, 6])

printer(
    'If you want to put insert_array into array, you would do it at these\n'
    'indices:\n%s',
    np.searchsorted(array, insert_array)
)

If you want to put insert_array into array, you would do it at these
indices:
[1 2 3]
