# NumPy Tutorial

https://www.w3schools.com/python/numpy/

## Array Reshaping

Reshaping arrays can mean:
- Adding/removing elements to a dimension
- Adding/removing dimensions

### Reshape from 1D to 2D

Use the `.reshape()` method. Specify the number of elements to have in each dimension, from the outside in (e.g., ending with columns).

In [4]:
import numpy as np
from configurations import printer

printer('Making array_1D')
array_1D = np.array([*range(1, 61)])
printer('array_1D has %s dimensions', array_1D.ndim)
printer('array_1D has shape: %s', array_1D.shape)
printer('array_1D is:\n%s\n', array_1D)

printer('Making array_2D based on array_1D')
array_2D = array_1D.reshape(2, 30)
printer('array_2D has %s dimensions', array_2D.ndim)
printer('array_2D has shape: %s', array_2D.shape)
printer('array_2D is:\n%s\n', array_2D)

printer('Making array_3D based on array_1D')
array_3D = array_1D.reshape(3, 4, 5)
printer('array_3D has %s dimensions', array_3D.ndim)
printer('array_3D has shape: %s', array_3D.shape)
printer('array_3D is:\n%s\n', array_3D)

printer('Making array_4D based on array_1D')
array_4D = array_1D.reshape(2, 2, 3, 5)
printer('array_4D has %s dimensions', array_4D.ndim)
printer('array_4D has shape: %s', array_4D.shape)
printer('array_4D is:\n%s\n', array_4D)

Making array_1D
array_1D has 1 dimensions
array_1D has shape: (60,)
array_1D is:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]

Making array_2D based on array_1D
array_2D has 2 dimensions
array_2D has shape: (2, 30)
array_2D is:
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54
  55 56 57 58 59 60]]

Making array_3D based on array_1D
array_3D has 3 dimensions
array_3D has shape: (3, 4, 5)
array_3D is:
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]

Making array_4D based on array_1D
array_4D has 4 dimensions
array_4D has shape: (2, 2, 3, 5)
array_4D i

### Can We Reshape Into any Shape?

You can reshape to any shape where the final shapes are equal in sizes. If you try to reshape to a shape that does not work, you will get an error.

In [7]:
import numpy as np
from configurations import logger

array_1D = np.array([*range(1, 11)])

array_2D = array_1D.reshape(2, 5)

try:
    array_3D = array_1D.reshape(3, 3)
except ValueError as exception:
    logger.error('Error raised: %s', exception)


2023-07-31 15:43:20 
	Logger: numpy-tutorial Module: 175190301 Function: <module> File: 175190301.py Line: 11
ERROR:
Error raised: cannot reshape array of size 10 into shape (3,3)



### Returns Copy or View?

When you reshape, you get a view of the original dataset, not a copied dataset.

In [8]:
import numpy as np
from configurations import printer

printer('Making array_1D')
array_1D = np.array([*range(1, 11)])

printer('Making array_2D')
array_2D = array_1D.reshape(2, 5)

printer('Checking base of array_2D: %s', array_2D.base)

printer('Updating a value in array_1D to see effects on array_2D')
array_1D[0] = 42
printer('array_1D is:\n%s', array_1D)
printer('array_2D is:\n%s', array_2D)

Making array_1D
Making array_2D
Checking base of array_2D: [ 1  2  3  4  5  6  7  8  9 10]
Updating a value in array_1D to see effects on array_2D
array_1D is:
[42  2  3  4  5  6  7  8  9 10]
array_2D is:
[[42  2  3  4  5]
 [ 6  7  8  9 10]]


### Unknown Dimension

When reshaping, you can leave size of the final dimension unspecified. This is because by specifying all of the other dimensions, only one possible value remains for the final dimension anyways, so it is inferred by numpy.

To do this, specify the unknown dimension with `-1`.

In [10]:
import numpy as np
from configurations import printer

printer('Making array_1D')
array_1D = np.array([*range(1, 11)])

printer('Making array_2D')
array_2D = array_1D.reshape(2, -1)

printer('array_1D is:\n%s', array_1D)
printer('array_2D is:\n%s', array_2D)

Making array_1D
Making array_2D
array_1D is:
[ 1  2  3  4  5  6  7  8  9 10]
array_2D is:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Flattening the arrays

If you want to collapse a multidimensional array to a 1D array, use `.reshape(-1)`.

In [11]:
import numpy as np
from configurations import printer

printer('Making array_1D')
array_1D = np.array([*range(1, 61)])

printer('Making array_2D based on array_1D')
array_2D = array_1D.copy().reshape(2, 30)

printer('Making array_3D based on array_1D')
array_3D = array_1D.copy().reshape(3, 4, 5)

printer('Making array_4D based on array_1D')
array_4D = array_1D.copy().reshape(2, 2, 3, 5)

printer('\narray_4D is:\n%s', array_4D)

printer('Making array_1D_remade from array_4D')
array_1D_remade = array_4D.reshape(-1)

printer('\narray_1D_remade is:\n%s', array_1D_remade)

Making array_1D
Making array_2D based on array_1D
Making array_3D based on array_1D
Making array_4D based on array_1D

array_4D is:
[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [11 12 13 14 15]]

  [[16 17 18 19 20]
   [21 22 23 24 25]
   [26 27 28 29 30]]]


 [[[31 32 33 34 35]
   [36 37 38 39 40]
   [41 42 43 44 45]]

  [[46 47 48 49 50]
   [51 52 53 54 55]
   [56 57 58 59 60]]]]
Making array_1D_remade from array_4D

array_1D_remade is:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]


Other functions for reshaping that fall into the intermediate or advanced categories include:
- `.flatten()`: apparently collapses n-dimensional arrays to 1D
- `.ravel()`: apparently collapses n-dimensional arrays based on logic used in other languages such as C and Fortran ([reference](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html))
- `np.rot90()`: rotates arrays 90 degrees. Has somewhat intuitive behavior for 2D arrays (rotating 90-degrees counterclockwise, not clockwise), and less-intuitive for higher-order arrays
- `np.flip()`: reverses the order of all elements in all arrays
- `np.fliplr()`: in 2D array, behavior is intuitive, flipping left-to-right within rows. On higher-order arrays, it is less intuitive.
- `np.flipup()`: in 2D array, behavior is intuitive, flipping top-to-bottom within columns. In a 1D array, the behavior is non-intuitive, since it seems to flip data left-to-right, but the `np.fliplr()` will not work on 1D arrays. On higher-order arrays, it is less intuitive.


In [31]:
import numpy as np
from configurations import printer

printer('Making array_1D')
array_1D = np.array([*range(1, 61)])
printer('\narray_1D:\n%s', array_1D)
printer('\nnp.flip(array_1D):\n%s', np.flip(array_1D))
printer('\nnp.flipud(array_1D):\n%s', np.flipud(array_1D))


printer('\nMaking array_2D based on array_1D')
array_2D = array_1D.copy().reshape(2, 30)
printer('\narray_2D is:\n%s', array_2D)
printer('\nnp.flip(array_2D):\n%s', np.flip(array_2D))
printer('\nnp.fliplr(array_2D):\n%s', np.fliplr(array_2D))
printer('\nnp.flipud(array_2D):\n%s', np.flipud(array_2D))
printer('\narray_2D.flatten():\n%s', array_2D.flatten())
printer('\nnp.rot90(array_2D):\n%s', np.rot90(array_2D))

printer('\nMaking array_3D based on array_1D')
array_3D = array_1D.copy().reshape(3, 4, 5)
printer('\narray_3D is:\n%s', array_3D)
printer('\narray_3D.flatten():\n%s', array_3D.flatten())
printer('\nnp.flip(array_3D):\n%s', np.flip(array_3D))
printer('\nnp.fliplr(array_3D):\n%s', np.fliplr(array_3D))
printer('\nnp.flipud(array_3D):\n%s', np.flipud(array_3D))
printer('\nnp.rot90(array_3D):\n%s', np.rot90(array_3D))


printer('\nMaking array_4D based on array_1D')
array_4D = array_1D.copy().reshape(2, 2, 3, -1)
printer('\narray_4D is:\n%s', array_4D)
printer('\narray_4D.flatten():\n%s', array_4D.flatten())
printer('\nnp.flip(array_4D):\n%s', np.flip(array_4D))
printer('\nnp.fliplr(array_4D):\n%s', np.fliplr(array_4D))
printer('\nnp.flipud(array_4D):\n%s', np.flipud(array_4D))
printer('\nnp.rot90(array_4D):\n%s', np.rot90(array_4D))

Making array_1D

array_1D:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]

np.flip(array_1D):
[60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37
 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13
 12 11 10  9  8  7  6  5  4  3  2  1]

np.flipud(array_1D):
[60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37
 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13
 12 11 10  9  8  7  6  5  4  3  2  1]

Making array_2D based on array_1D

array_2D is:
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54
  55 56 57 58 59 60]]

np.flip(array_2D):
[[60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37
  36 35 34 33 32 31]
 [30 29 28 27 26 25 24 2