# NumPy Tutorial

https://www.w3schools.com/python/numpy/

## Splitting Array

Splitting is the inverse of joining.

Use `array_split()`, specifying the array and the number of splits.

The splits are dropped into a list.

In [1]:
import numpy as np
from configurations import printer, logger

array = np.array([*range(1, 7)])
printer('The array is:\n%s', array)
split_2 = np.array_split(array, 2)
printer('The array split into 2 is:\n%s', split_2)
printer('The type of split_2 is:\n%s', type(split_2))

split_3 = np.array_split(array, 3)
printer('The array split into 3 is:\n%s',split_3)
printer('The type of split_3 is:\n%s', type(split_3))

logger.info(
    'It is no problem if you specify a number of splits that do not match\n'
    'evenly into the number of elements in the array. The splits will be\n'
    'made to be equal-sized until they cannot any longer.'
)
split_4 = np.array_split(array, 4)
printer('The array split into 4 is:\n%s',split_4)
printer('The type of split_4 is:\n%s', type(split_4))

logger.info(
    'If you only want it to split if you have equal-sized new arrays,\n'
    'use the np.split() function instead, which will throw an error when\n'
    'it cannot make equal-sized new arrays'
)

try:
    other_split_4 = np.split(array, 4)
except ValueError as exception:
    logger.error(exception)

The array is:
[1 2 3 4 5 6]
The array split into 2 is:
[array([1, 2, 3]), array([4, 5, 6])]
The type of split_2 is:
<class 'list'>
The array split into 3 is:
[array([1, 2]), array([3, 4]), array([5, 6])]
The type of split_3 is:
<class 'list'>

2023-07-31 19:08:01 
	Logger: numpy-tutorial Module: 2821216378 Function: <module> File: 2821216378.py Line: 14
INFO:
It is no problem if you specify a number of splits that do not match
evenly into the number of elements in the array. The splits will be
made to be equal-sized until they cannot any longer.

The array split into 4 is:
[array([1, 2]), array([3, 4]), array([5]), array([6])]
The type of split_4 is:
<class 'list'>

2023-07-31 19:08:01 
	Logger: numpy-tutorial Module: 2821216378 Function: <module> File: 2821216378.py Line: 23
INFO:
If you only want it to split if you have equal-sized new arrays,
use the np.split() function instead, which will throw an error when
it cannot make equal-sized new arrays


2023-07-31 19:08:01 
	Logger: nump

### Split Into Arrays

The split arrays land in an array-like list, and thus can be accessed via normal indexing methods.

You will see that although the split arrays land in a list, they are arrays in their own right.

In [20]:
import numpy as np
from configurations import printer

array = np.array([*range(1, 7)])
printer('The array is:\n%s', array)
split_2 = np.array_split(array, 2)
printer('The array split into 2 is:\n%s', split_2)
printer('The type of split_2 is:\n%s', type(split_2))

split_2_element_0 = split_2[0]
split_2_element_1 = split_2[1]
printer('split_2_element_0 is:\n%s', split_2_element_0)
printer('Type of split_2_element_0 is:\n%s', type(split_2_element_0))
printer('Type of split_2_element_1 is:\n%s', type(split_2_element_1))

The array is:
[1 2 3 4 5 6]
The array split into 2 is:
[array([1, 2, 3]), array([4, 5, 6])]
The type of split_2 is:
<class 'list'>
split_2_element_0 is:
[1 2 3]
Type of split_2_element_0 is:
<class 'numpy.ndarray'>
Type of split_2_element_1 is:
<class 'numpy.ndarray'>


### Splitting 2-D Arrays

`np.array_split` works on 2D arrays also.

The split will behave differently based on the size/structure of the array and the number of splits you specify.

Also, if you use the `axis` argument, you can specify which axis to do the splits on --- recall that the default is `axis=0`, which splits on the most superficial axis.

In [11]:
import numpy as np
from configurations import printer

array = np.array([
    [*range(1, 4)],
    [*range(4, 7)],
    [*range(7, 10)],
    [*range(10, 13)],
    [*range(13, 16)],
    [*range(16, 19)]
    ])
printer('The array is:\n%s', array)
split_2 = np.array_split(array, 2)
split_2_a1 = np.array_split(array, 2, axis=1)
printer('The array split into 2 is:\n%s', split_2)
printer('The array split into 2 on axis 1 is:\n%s', split_2_a1)

split_3 = np.array_split(array, 3)
split_3_a1 = np.array_split(array, 3, axis=1)
printer('The array split into 3 is:\n%s', split_3)
printer('The array split into 3 on axis 1 is:\n%s', split_3_a1)

The array is:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
The array split into 2 is:
[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]
The array split into 2 on axis 1 is:
[array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11],
       [13, 14],
       [16, 17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
The array split into 3 is:
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
The array split into 3 on axis 1 is:
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


One may also use `hsplit`, `vsplit`, and `dsplit`.

Unfortunately, I did not make much sense of their names when trying to use these splits on 2D or 3D arrays, as they were not splitting arrays in ways that appeared to correspond to vertical, horizontal, or 'depth', to me.


In [26]:
import numpy as np
from configurations import printer, logger

array = np.array([
        [
            [*range(1, 5)],
            [*range(5, 9)]
        ],
        [
            [*range(9, 13)],
            [*range(13, 17)]
        ],
        [
            [*range(17, 21)],
            [*range(21, 25)]
        ]
    ])
printer('The array is:\n%s', array)
hsplit_2 = np.hsplit(array, 2)
printer('The array split into 2 with hsplit is:\n%s', hsplit_2)
dsplit_2 = np.dsplit(array, 2)
printer('The array split into 2 with dsplit is:\n%s', dsplit_2)

logger.warning(
    'I had iterated on other array sizes and shapes but never made much sense\n'
    'of their behavior or naming'
)

The array is:
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
The array split into 2 with hsplit is:
[array([[[ 1,  2,  3,  4]],

       [[ 9, 10, 11, 12]],

       [[17, 18, 19, 20]]]), array([[[ 5,  6,  7,  8]],

       [[13, 14, 15, 16]],

       [[21, 22, 23, 24]]])]
The array split into 2 with dsplit is:
[array([[[ 1,  2],
        [ 5,  6]],

       [[ 9, 10],
        [13, 14]],

       [[17, 18],
        [21, 22]]]), array([[[ 3,  4],
        [ 7,  8]],

       [[11, 12],
        [15, 16]],

       [[19, 20],
        [23, 24]]])]
