# NumPy Tutorial

https://www.w3schools.com/python/numpy/

## Splitting Array

Splitting is the inverse of joining.

Use `array_split()`, specifying the array and the number of splits.

The splits are dropped into a list.

In [1]:
import numpy as np
from configurations import printer, logger

array = np.array([*range(1, 7)])
printer('The array is:\n%s', array)
split_2 = np.array_split(array, 2)
printer('The array split into 2 is:\n%s', split_2)
printer('The type of split_2 is:\n%s', type(split_2))

split_3 = np.array_split(array, 3)
printer('The array split into 3 is:\n%s',split_3)
printer('The type of split_3 is:\n%s', type(split_3))

logger.info(
    'It is no problem if you specify a number of splits that do not match\n'
    'evenly into the number of elements in the array. The splits will be\n'
    'made to be equal-sized until they cannot any longer.'
)
split_4 = np.array_split(array, 4)
printer('The array split into 4 is:\n%s',split_4)
printer('The type of split_4 is:\n%s', type(split_4))

logger.info(
    'If you only want it to split if you have equal-sized new arrays,\n'
    'use the np.split() function instead, which will throw an error when\n'
    'it cannot make equal-sized new arrays'
)

try:
    other_split_4 = np.split(array, 4)
except ValueError as exception:
    logger.error(exception)

The array is:
[1 2 3 4 5 6]
The array split into 2 is:
[array([1, 2, 3]), array([4, 5, 6])]
The type of split_2 is:
<class 'list'>
The array split into 3 is:
[array([1, 2]), array([3, 4]), array([5, 6])]
The type of split_3 is:
<class 'list'>

2023-07-31 19:08:01 
	Logger: numpy-tutorial Module: 2821216378 Function: <module> File: 2821216378.py Line: 14
INFO:
It is no problem if you specify a number of splits that do not match
evenly into the number of elements in the array. The splits will be
made to be equal-sized until they cannot any longer.

The array split into 4 is:
[array([1, 2]), array([3, 4]), array([5]), array([6])]
The type of split_4 is:
<class 'list'>

2023-07-31 19:08:01 
	Logger: numpy-tutorial Module: 2821216378 Function: <module> File: 2821216378.py Line: 23
INFO:
If you only want it to split if you have equal-sized new arrays,
use the np.split() function instead, which will throw an error when
it cannot make equal-sized new arrays


2023-07-31 19:08:01 
	Logger: nump

### Split Into Arrays

The split arrays land in an array-like list, and thus can be accessed via normal indexing methods.

You will see that although the split arrays land in a list, they are arrays in their own right.

In [20]:
import numpy as np
from configurations import printer

array = np.array([*range(1, 7)])
printer('The array is:\n%s', array)
split_2 = np.array_split(array, 2)
printer('The array split into 2 is:\n%s', split_2)
printer('The type of split_2 is:\n%s', type(split_2))

split_2_element_0 = split_2[0]
split_2_element_1 = split_2[1]
printer('split_2_element_0 is:\n%s', split_2_element_0)
printer('Type of split_2_element_0 is:\n%s', type(split_2_element_0))
printer('Type of split_2_element_1 is:\n%s', type(split_2_element_1))

The array is:
[1 2 3 4 5 6]
The array split into 2 is:
[array([1, 2, 3]), array([4, 5, 6])]
The type of split_2 is:
<class 'list'>
split_2_element_0 is:
[1 2 3]
Type of split_2_element_0 is:
<class 'numpy.ndarray'>
Type of split_2_element_1 is:
<class 'numpy.ndarray'>


### Splitting 2-D Arrays

`split`