# NumPy Tutorial

https://www.w3schools.com/python/numpy/

## Sorting Arrays

The numpy function `sort()` will sort an array.


In [1]:
import numpy as np
from configurations import printer

array = np.array([3, 0, 2, 1])

printer('The array is:\n%s', array)
printer('The sorted array is:\n%s', np.sort(array))
    

The array is:
[3 0 2 1]
The sorted array is:
[0 1 2 3]


Arrays can be sorted not just numerically, but also alphabetically, or by other datatypes.

In [5]:
import numpy as np
from configurations import printer, logger

array = np.array(['h', 'i', 'b', 'a'])
printer('The array is:\n%s', array)
printer('The sorted array is:\n%s', np.sort(array))
    
boolean_array = np.array([False, True, False])
printer('The array is:\n%s', boolean_array)
printer('The sorted array is:\n%s', np.sort(boolean_array))

logger.info(
    'Sorting array with mixed types will first coerce to the same types'
    )
mixed_types_array = np.array(['h', 'i', 1, 'a'])
printer('The array is:\n%s', mixed_types_array)
printer('The sorted array is:\n%s', np.sort(mixed_types_array))

The array is:
['h' 'i' 'b' 'a']
The sorted array is:
['a' 'b' 'h' 'i']
The array is:
[False  True False]
The sorted array is:
[False False  True]

2023-08-01 07:27:13 
	Logger: numpy-tutorial Module: 2288051270 Function: <module> File: 2288051270.py Line: 12
INFO:
Sorting array with mixed types will first coerce to the same types

The array is:
['h' 'i' '1' 'a']
The sorted array is:
['1' 'a' 'h' 'i']


### Sorting a 2D Array

Sorting a 2D array will sort elements within the deepest dimension of the array.

In [11]:
import numpy as np
from configurations import printer, logger

array_2D = np.array([
    [8, 9, 2, 3],
    [0, 20, 13, 4]
])

printer('The array is:\n%s', array_2D)
printer('The sorted array is:\n%s', np.sort(array_2D))

array_3D = np.array([
    [
        [8, 9, 2, 3],
        [0, 20, 13, 4]
    ],
    [
        ['d', 'e', 'a', 'd'],
        ['F', 'f', 'g', 'G']
    ]
])

logger.info(
    'Capitals are sorted before lower case. Sorting works on higher-D arrays'
    )
printer('The array is:\n%s', array_3D)
printer('The sorted array is:\n%s', np.sort(array_3D))

The array is:
[[ 8  9  2  3]
 [ 0 20 13  4]]
The sorted array is:
[[ 2  3  8  9]
 [ 0  4 13 20]]

2023-08-01 07:32:10 
	Logger: numpy-tutorial Module: 1895735294 Function: <module> File: 1895735294.py Line: 23
INFO:
Capitals are sorted before lower case. Sorting works on higher-D arrays

The array is:
[[['8' '9' '2' '3']
  ['0' '20' '13' '4']]

 [['d' 'e' 'a' 'd']
  ['F' 'f' 'g' 'G']]]
The sorted array is:
[[['2' '3' '8' '9']
  ['0' '13' '20' '4']]

 [['a' 'd' 'd' 'e']
  ['F' 'G' 'f' 'g']]]
