# NumPy Tutorial

https://www.w3schools.com/python/numpy/

## Array Indexing

### Access Array Elements

This works like you are used to with indexing `list` or other ordered collections.

In [15]:
import numpy as np
from configurations import printer

array = np.array(range(1, 6))

printer('The 0th item in the array is %s', array[0])
printer('The -1st item in the array is %s', array[-1])
printer('The ~0th item in the array is %s', array[~0])

printer('The 0th up to the 2nd item in the array is %s', array[0:2])
printer('The -3rd up to the -1st item in the array is %s', array[-3:-1])
printer('The ~2nd up to the ~0th item in the array is %s', array[~2:~0])

unpacked_array = np.array([*range(1, 6)])

printer('The 0th item in the unpacked_array is %s', unpacked_array[0])
printer('The -1st item in the unpacked_array is %s', unpacked_array[-1])
printer('The ~0th item in the unpacked_array is %s', unpacked_array[~0])

printer('The 0th up to the 2nd item in the unpacked_array is %s', unpacked_array[0:2])
printer('The -3rd up to the -1st item in the unpacked_array is %s', unpacked_array[-3:-1])
printer('The ~2nd up to the ~0th item in the unpacked_array is %s', unpacked_array[~2:~0])

The 0th item in the array is 1
The -1st item in the array is 5
The ~0th item in the array is 5
The 0th up to the 2nd item in the array is [1 2]
The -3rd up to the -1st item in the array is [3 4]
The ~2nd up to the ~0th item in the array is [3 4]
The 0th item in the unpacked_array is 1
The -1st item in the unpacked_array is 5
The ~0th item in the unpacked_array is 5
The 0th up to the 2nd item in the unpacked_array is [1 2]
The -3rd up to the -1st item in the unpacked_array is [3 4]
The ~2nd up to the ~0th item in the unpacked_array is [3 4]


Note that `np.array` will unpack a `range` object automatically. This means it will create an array from it by default, which works well when creating a 1-D array.

However, if you wrap a range object in square brackets, then you will need to explicitly unpack the `range` object with the unpacking operator, `*`.

When creating higher-dimensional arrays, the syntax is to start with square brackets and use commas to separate the different elements in the higher dimensions. Since the square-brackets are required for building these higher-order arrays, it also necessitates using the unpacking operator, `*`, when using the `range` objects in these higher-order arrays.

In [23]:
import numpy as np
from configurations import printer

array_1D = np.array(range(1, 6))
printer('array_1D is %s', array_1D)

alternative_1D_array = np.array([*range(1, 6)])
printer('alternative_1D_array is %s', alternative_1D_array)

array_2D = np.array([
    [*range(1, 6)], [*range(6, 11)]
    ])
printer('array_2D is\n%s', array_2D)

array_1D is [1 2 3 4 5]
alternative_1D_array is [1 2 3 4 5]
array_2D is
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Access 2-D Arrays

When an array has more than 1 dimension, accessing items in the indices is done with a comma-separated syntax.

For example, `array[0, 1]` will access the 0th element from dimension 1 and the 1st element from dimension 2.

In the case of a 2-D array, dimension 1 can be thought of as rows, and dimension 2 can be thought of as columns.

#### Conceptualizing how dimensions shift as more dimensions are added

Typically we think of a number line being visualized horizontally, which is 1-D. The numbers on a number line correspond roughly with columns in a table (also displayed horizontally). Thus, dimension 1 (the only dimension) in a 1-D array are like columns.

As a 1-D array is extended to the 2-D case, the columns still exist, but now a new dimension, rows are added. The newest dimension becomes the first dimension accessed in array indexing. This means that the more primitive dimension, columns, gets 'promoted' to a higher dimension. The same occurs as you extend a 2-D array to a 3-D array; all of the existing arrays get 'promoted' and the newest dimension added becomse the first one accessed.

This can also be thought of as needing to 'drill down' through dimensions to get to the most primitive dimensions; the number of dimensions you need to drill through before you get to the 'columns' is equal to the number of dimensions in the array (1-D array means 1 dimension must be traversed; 2-D array means 2 dimensions must be traversed, etc.). This can also be thought of the number of open square brackets that must be passed before accessing the dimension.

Hopefully this table can help with the conceptualization.

| N-dims | Columns dim. | Rows dim. | Tables dim. |
| ------ | ------------ | --------- | ----------- |
| 0      | NA           | NA        | NA          |
| 1      | 1            | NA        | NA          |
| 2      | 2            | 1         | NA          |
| 3      | 3            | 2         | 1           |

In [32]:
import numpy as np
from configurations import printer, logger

array = np.array([
    [*range(1, 6)],
    [*range(6, 11)]
    ])

printer('The array is\n%s', array)
printer('The item in position [0, 0] is %s', array[0, 0])
printer('The item in position [-1, 0] is %s', array[-1, 0])
printer('The item in position [0, -1] is %s', array[0, -1])
printer('The item in position [~0, 0] is %s', array[~0, 0])
printer('The item in position [0, ~0] is %s', array[0, ~0])

printer('\n')
printer('The items in position [0:2, 0:2] are\n%s', array[0:2, 0:2])

logger.warning(
               '\nSlicing using negative indexing in multi-dimensional arrays'
               'does not behave as I would have expected; avoid it! for now!'
               )

printer('The item in position [-3:-1, -3:-1] are \n %s', array[-3:-1, -3:-1])
printer('The item in position [~2:~0, ~2:~0] are \n %s', array[~2:~0, ~2:~0])

The array is
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
The item in position [0, 0] is 1
The item in position [-1, 0] is 6
The item in position [0, -1] is 5
The item in position [~0, 0] is 6
The item in position [0, ~0] is 5


The items in position [0:2, 0:2] are
[[1 2]
 [6 7]]

2023-07-31 11:12:18 
	Logger: numpy-tutorial Module: 1953604793 Function: <module> File: 1953604793.py Line: 19

The negative indexing of multi-dimensional arrays does notbehave as I would have expected, thus it should be avoided.
The item in position [-3:-1, -3:-1] are 
 [[3 4]]
The item in position [~2:~0, ~2:~0] are 
 [[3 4]]


### Access 3-D Arrays

Continue the same pattern, using `ndarray[int, int, int, ...]` to access elements from higher-dimensional arrays.

Dimension 1 is the most nested. Thus, `ndarray[0, 1, 2]` in a 3-D array would access the element from the 0th row in the 1st column in the 2nd 2-D array (keeping in mind 0-indexing).

In [33]:
import numpy as np
from configurations import printer

array = np.array([
    [
        [*range(1, 6)],
        [*range(6, 11)]
    ],
        [
        [*range(11, 16)],
        [*range(16, 21)]
    ]
    ])

printer('The array is\n%s', array)
printer('The item in position [0, 0, 0] is %s', array[0, 0, 0])
printer('The item in position [1, 0, 0] is %s', array[1, 0, 0])
printer('The item in position [0, 1, 0] is %s', array[0, 1, 0])
printer('The item in position [0, 0, 1] is %s', array[0, 0, 1])

printer('\nThe item in position [1, 1, 0] is %s', array[1, 1, 0])
printer('The item in position [1, 0, 1] is %s', array[1, 0, 1])
printer('The item in position [0, 1, 1] is %s', array[0, 1, 1])

printer('\nThe item in position [-1, 0, 0] is %s', array[-1, 0, 0])
printer('The item in position [0, -1, 0] is %s', array[0, -1, 0])
printer('The item in position [0, 0, -1] is %s', array[0, 0, -1])

printer('\nThe item in position [-1, -1, 0] is %s', array[-1, -1, 0])
printer('The item in position [-1, 0, -1] is %s', array[-1, 0, -1])
printer('The item in position [0, -1, -1] is %s', array[0, -1, -1])

The array is
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
The item in position [0, 0, 0] is 1
The item in position [1, 0, 0] is 11
The item in position [0, 1, 0] is 6
The item in position [0, 0, 1] is 2

The item in position [1, 1, 0] is 16
The item in position [1, 0, 1] is 12
The item in position [0, 1, 1] is 7

The item in position [-1, 0, 0] is 11
The item in position [0, -1, 0] is 6
The item in position [0, 0, -1] is 5

The item in position [-1, -1, 0] is 16
The item in position [-1, 0, -1] is 15
The item in position [0, -1, -1] is 10
