# NumPy Tutorial

https://www.w3schools.com/python/numpy/

## Filtering Arrays

In NumPy, filters are done based on boolean logic. That is, if a boolean test evaluates to `True` at an index, then it will be kept after the filter. If the boolean test evaluates to `False`, then it will not be kept; i.e., it will be filtered out.

In [1]:
import numpy as np
from configurations import printer

array = np.array([41, 42, 43, 44])

boolean_array = np.array([False, True, False, False])

printer('Array is:\n%s', array)
printer('boolean_array is:\n%s', boolean_array)
printer(
    'Filtering array based on booleans in boolean array yields:\n%s',
    array[boolean_array]
)

Array is:
[41 42 43 44]
boolean_array is:
[False  True False False]
Filtering array based on booleans in boolean array yields:
[42]


### Creating the Filter Array

In the previous example, an array was made manually and explicitly. However, it is more common to create it programmatically. For example, by creating an array-like object such as a list.

In [3]:
import numpy as np
from configurations import printer

array = np.array([41, 42, 43, 44])

true_if_42 = [True if element == 42 else False for element in array]

printer('Array is:\n%s', array)
printer('true_if_42 is:\n%s', true_if_42)
printer(
    'Filtering array based on booleans in true_if_42 array yields:\n%s',
    array[true_if_42]
)

true_if_even = [True if element % 2 == 0 else False for element in array]

printer('Array is:\n%s', array)
printer('true_if_even is:\n%s', true_if_even)
printer(
    'Filtering array based on booleans in true_if_even array yields:\n%s',
    array[true_if_even]
)

Array is:
[41 42 43 44]
true_if_42 is:
[False, True, False, False]
Filtering array based on booleans in true_if_42 array yields:
[42]
Array is:
[41 42 43 44]
true_if_even is:
[False, True, False, True]
Filtering array based on booleans in true_if_even array yields:
[42 44]


### Creating Fliter Directly From Array

In numpy, if you want to filter an array, you do not need to go through the process of first creating the filter array and then substituting it into the square brackets to subset the original array (as you have done in the previous code cells in this notebook); a more succinct way is to do the same is to just put the boolean logic directly into the square brackets for filtering.

In [7]:
import numpy as np
from configurations import printer

array = np.array([*range(41, 45)])

printer('The array is:\n%s', array)
printer('The array filtered where values are 42 is:\n%s', array[array == 42])
printer(
    'The array filtered where values are even is:\n%s',
    array[array % 2 == 0]
    )

The array is:
[41 42 43 44]
The array filtered where values are 42 is:
[42]
The array filtered where values are even is:
[42 44]


What is good to know about filtering numpy arrays is that the filtered arrays are their own objects in memory; they are not just views on the original array.

In [3]:
import numpy as np
from configurations import printer

array = np.array([*range(41, 45)])

array_42 = array[array == 42]
array_even= array[array % 2 == 0]

printer('Array is:\n%s', array)
printer('array_42 is:\n%s', array_42)
printer('array_even is:\n%s', array_even)
printer('Base of array is:\n%s', array.base)
printer('Base of array_42 is:\n%s', array_42.base)
printer('Base of array_even is:\n%s', array_even.base)

printer('Updating a value in array_even')
array_even[0] = 77

printer('array_even is:\n%s', array_even)
printer('Array is not affected by the update. It is still:\n%s', array)

Array is:
[41 42 43 44]
array_42 is:
[42]
array_even is:
[42 44]
Base of array is:
None
Base of array_42 is:
None
Base of array_even is:
None
Updating a value in array_even
array_even is:
[77 44]
Array is not affected by the update. It is still:
[41 42 43 44]
