# NumPy Tutorial

https://www.w3schools.com/python/numpy/

## Array Indexing

### Slicing array

Slicing should behave the same as you are used to with other collections, using the syntax `[start:end:step]`.

In [4]:
import numpy as np
from configurations import printer

array = np.array(range(1, 6))

printer('Indices 1:2 are: %s', array[1:2])
printer('Indices :2 are: %s', array[:2])

Indices 1:2 are: [2]
Indices :2 are: [1 2]


### Negative Slicing

Use the `-` operator or the `~` operator depending on which you prefer.

In [5]:
import numpy as np
from configurations import printer

array = np.array(range(1, 6))

printer('Indices [-3:-2] are: %s', array[-3:-2])
printer('Indices [:-2] are: %s', array[:-2])

Indices [-3:-2] are: [3]
Indices [:-2] are: [1 2 3]


### Step

Use the step to indicate how large the steps should be between slicing. The default is 1.

In [6]:
import numpy as np
from configurations import printer

array = np.array(range(1, 10))

printer('Indices [-3:-2:2] are: %s', array[-3:-2:2])
printer('Indices [:-2:2] are: %s', array[:-2:2])

Indices [-3:-2:2] are: [7]
Indices [:-2:2] are: [1 3 5 7]


### Slicing 2-D Arrays

Just like indexing higher-level arrays, slicing them requires using comma separation, and the order of the dimensions you slice from are the same as if you were indexing.

Slicing with negative indices can be confusing due to the different behaviors of `-` and `~` operators and the different behaviors of the `[start:]` and `[:stop:]` positional arguments. Recall that `-1` = `~0` which means the final index in a collection, and that the `[:stop:]` value means up-to-but-not-including the value.

In [16]:
import numpy as np
from configurations import printer

array = np.array([
    [
        [*range(1, 6)],
        [*range(6, 11)]
    ],
        [
        [*range(11, 16)],
        [*range(16, 21)]
    ]
    ])

printer('The array is\n%s\n', array)
printer('The slice [0:1, 0:1, 0:1] is\n%s\n', array[0:1, 0:1, 0:1])
printer('The slice [0:1, 0:1, 0:3] is\n%s\n', array[0:1, 0:1, 0:3])
printer('The slice [0:1, 0:2, 0:3] is\n%s\n', array[0:1, 0:2, 0:3])
printer('The slice [0:2, 0:2, 0:3] is\n%s\n', array[0:2, 0:2, 0:3])

printer('\n\nNow onto negative sliding!\n\n')
printer('The slice [0:1, 0:1, 0:-1] is\n%s\n', array[0:1, 0:1, 0:-1])
printer('The slice [0:1, 0:1, 0:~0] is\n%s\n', array[0:1, 0:1, 0:~0])
printer('The slice [0:1, 0:1, 0:~1] is\n%s\n', array[0:1, 0:1, 0:~1])
printer('The slice [0:1, 0:1, ~5:] is\n%s\n', array[0:1, 0:1, ~5:])
printer('The slice [0:1, 0:1, 0:-0] is\n%s\n', array[0:1, 0:1, 0:-0])
# printer('The slice [0:1, 0:2, 0:3] is\n%s\n', array[0:1, 0:2, 0:3])
# printer('The slice [0:2, 0:2, 0:3] is\n%s\n', array[0:2, 0:2, 0:3])


The array is
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]

The slice [0:1, 0:1, 0:1] is
[[[1]]]

The slice [0:1, 0:1, 0:3] is
[[[1 2 3]]]

The slice [0:1, 0:2, 0:3] is
[[[1 2 3]
  [6 7 8]]]

The slice [0:2, 0:2, 0:3] is
[[[ 1  2  3]
  [ 6  7  8]]

 [[11 12 13]
  [16 17 18]]]



Now onto negative sliding!


The slice [0:1, 0:1, 0:-1] is
[[[1 2 3 4]]]

The slice [0:1, 0:1, 0:~0] is
[[[1 2 3 4]]]

The slice [0:1, 0:1, 0:~1] is
[[[1 2 3]]]

The slice [0:1, 0:1, ~5:] is
[[[1 2 3 4 5]]]

The slice [0:1, 0:1, 0:-0] is
[]

