# NumPy Tutorial

https://www.w3schools.com/python/numpy/

## Creating Arrays

### Create a NumPy `ndarray` Object

Use the `array()` function.

Array-like objects like (e.g., `list`, `tuple`, `set`) can be coerced into an `ndarray` with the `array()` function.

Note that the print method for an `ndarray` built from a set differs, having curly brackets.

In [10]:
import numpy as np
from configurations import printer

my_range = range(1, 6)
printer('Type of my_range is %s', type(my_range))
array_from_range = np.array(my_range)
printer('Type of array_from_range is %s', type(array_from_range))
printer(array_from_range)

my_list = list(my_range)
printer('Type of my_list is %s', type(my_list))
array_from_list = np.array(my_list)
printer('Type of array_from_list is %s', type(array_from_list))
printer(array_from_list)

my_tuple = tuple(my_range)
printer('Type of my_tuple is %s', type(my_tuple))
array_from_tuple = np.array(my_tuple)
printer('Type array_from_tuple is %s', type(array_from_tuple))
printer(array_from_tuple)

my_set = set(my_range)
printer('Type of my_set is %s', type(my_set))
array_from_set = np.array(my_set)
printer('Type array_from_set is %s', type(array_from_set))
printer(array_from_set)


Type of my_range is <class 'range'>
Type of array_from_range is <class 'numpy.ndarray'>
[1 2 3 4 5]
Type of my_list is <class 'list'>
Type of array_from_list is <class 'numpy.ndarray'>
[1 2 3 4 5]
Type of my_tuple is <class 'tuple'>
Type array_from_tuple is <class 'numpy.ndarray'>
[1 2 3 4 5]
Type of my_set is <class 'set'>
Type array_from_set is <class 'numpy.ndarray'>
{1, 2, 3, 4, 5}


### Dimensions in Arrays

One level of 'array depth' is one dimension. An array can be nested in another array, giving you a 2-dimensional array. Another level of nesting would be a 3-dimensional array.

Since numpy arrays can be basically up to any number of nesting, they are called `ndarray` objects for 'n-dimensional' arrays.


A 1-dimensional array with a single value is a 'scalar', and this is considered a 0-dimensional array, in fact.

The number of dimensions are in the attribute `.ndim`.

#### 0-D Arrays

In [11]:
import numpy as np
from configurations import printer

array = np.array(42)

printer('The type of array is %s', type(array))
printer('The array is %s', array)
printer('The number of dimensions are %s', array.ndim)

The type of array is <class 'numpy.ndarray'>
The array is 42
The dimensions are 0


#### 1-D Arrays

These are the most-frequent kind of arrays. They are arrays with more than one element.

In [12]:
import numpy as np
from configurations import printer

array = np.array(list(range(1, 6)))

printer('The type of array is %s', type(array))
printer('The array is %s', array)
printer('The number of dimensions are %s', array.ndim)

The type of array is <class 'numpy.ndarray'>
The array is [1 2 3 4 5]
The number of dimensions are 1


#### 2-D Arrays

These are often used to represent a table, like an excel spreadsheet.

A 2-D array is the same as a 2-D 'tensor'. It is simply the fact that the word 'tensor' is usually not used until arrays reach at least 2 dimensions, although 0-D and 1-D arrays are also tensors.

Note that when nesting arrays, they must-be comma-separated, just like the items in a 1-D array normally need to be comma-separated.

In [18]:
import numpy as np
from configurations import printer

array = np.array([
    [*range(1, 4)], [*range(4, 7)]
    ])

printer('The type of array is %s', type(array))
printer('The array is \n%s', array)
printer('The number of dimensions are %s', array.ndim)

The type of array is <class 'numpy.ndarray'>
The array is 
[[1 2 3]
 [4 5 6]]
The number of dimensions are 2


#### 3-D Arrays

An array that has 2-D arrays as its is a 3-D array (also known as a 3rd-order tensor).

In [19]:
import numpy as np
from configurations import printer

array = np.array([
    [
        [*range(1, 3)],
        [*range(3, 5)]
    ],
    [
        [*range(5, 7)],
        [*range(7, 9)]
    ]
    ])

printer('The type of array is %s', type(array))
printer('The array is \n%s', array)
printer('The number of dimensions are %s', array.ndim)

The type of array is <class 'numpy.ndarray'>
The array is 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
The number of dimensions are 3


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Higher Dimensional Arrays

You can specify the number of dimensions for an array at time of creation with the `ndim` argument.

If you do not populate all of the dimensions at time of creation even if you specify their existence, then the inner-most dimensions will be filled first.

In [24]:
import numpy as np
from configurations import printer

array = np.array(range(1, 6), ndmin=1)
printer('The type of array is %s', type(array))
printer('The array is \n%s', array)
printer('The number of dimensions are %s\n', array.ndim)

array = np.array(range(1, 6), ndmin=2)
printer('The type of array is %s', type(array))
printer('The array is \n%s', array)
printer('The number of dimensions are %s\n', array.ndim)

array = np.array([range(1, 6), range(6, 11)], ndmin=2)
printer('The type of array is %s', type(array))
printer('The array is \n%s', array)
printer('The number of dimensions are %s\n', array.ndim)

array = np.array([range(1, 6), range(6, 11)], ndmin=3)
printer('The type of array is %s', type(array))
printer('The array is \n%s', array)
printer('The number of dimensions are %s\n', array.ndim)

The type of array is <class 'numpy.ndarray'>
The array is 
[1 2 3 4 5]
The number of dimensions are 1

The type of array is <class 'numpy.ndarray'>
The array is 
[[1 2 3 4 5]]
The number of dimensions are 2

The type of array is <class 'numpy.ndarray'>
The array is 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
The number of dimensions are 2

The type of array is <class 'numpy.ndarray'>
The array is 
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
The number of dimensions are 3

