# NumPy Tutorial

https://www.w3schools.com/python/numpy/

## Exponential Distribution

This distribution is related to the Poisson distribution. In Poisson, you show the probability distribution of an event occurring within a certain dimension (time, space) if it has a known mean frequency. In the Exponential distribution, you show the probability distribution the dimension (e.g., time or space) before the next event occurrence.

See the [Wikipedia article here](https://en.wikipedia.org/wiki/Exponential_distribution).

The inverse of the rate is indicated with `scale` in `numpy.random.exponential()` and the `size` dictates the size of the returned array.

In [3]:
import numpy as np
from configurations import printer

scales_to_cycle_through = [1, 10, 100]
for scale in scales_to_cycle_through:
    my_array = np.random.exponential(scale=scale, size = 10)
    printer(
        'These are 10 examples of the results from an exponential\n'
        'distribution with scale = %s:\n%s\n'
        scale,
        my_array
        )

These are 10 examples of the results from a Poisson distribution
with lambda = 1:
[0 0 1 2 1 2 2 0 0 1]
They have mean: 0.9
These are 10 examples of the results from a Poisson distribution
with lambda = 10:
[13 10 23  4  9 11  5  9 13 10]
They have mean: 10.7
These are 10 examples of the results from a Poisson distribution
with lambda = 100:
[113 100  96 104 115  91 113 123  87 106]
They have mean: 104.8


### Visualization of the Exponential distribution

In [ ]:
import numpy as np
import seaborn as sns # type: ignore
import matplotlib.pyplot as plt
from configurations import logger

plt.style.use('my_mpl_stylesheet')

logger.warning(
    'Seaborn does not seem to export a stub to help linters with type hints\n'
    'so I am explicitly disabling type hints on those lines.'
)

logger.warning(
    'Matplotlib.pyplot does not seem to have types set up for linters.\n'
    'So I am explicitly disabling type hints on those lines.'
)

def plot_exponential(
    scale: float = 1,
    size: int = 1_000,
    bw_adjust: float = 1
    ) -> None:

    my_exponential = np.random.exponential(scale=scale, size=size)
    
    sns.histplot( # type: ignore
        my_exponential,
        ax=plt.subplots()[1], # type: ignore
        stat='probability',
        kde=True,
        kde_kws={'bw_adjust' : bw_adjust},
        edgecolor='None'
        )
    
    plt.title( # type: ignore
        label=f'{size:,} samples from an exponential distribution with\n'
        f'scale={scale:,.2f}'
        f'\nthus rate={1/scale:,.2f}',
        family='serif'
        )
    
    plt.xlabel(xlabel='Value of sample', family='sans-serif') # type: ignore
    
scales_bandwidths_to_cycle_through = {
    0.1 : 0.415,
    1 : 0.410,
    10 : 0.400
    }

for scale in scales_bandwidths_to_cycle_through:
    plot_exponential(
        scale=scale,
        bw_adjust=scales_bandwidths_to_cycle_through[scale]
        )