# NumPy Tutorial

https://www.w3schools.com/python/numpy/

## Random Numbers in Numpy

For a useful discussion on the differences between the in-built `random` module and the `numpy.random` module, see [this Stack Overflow page](https://stackoverflow.com/questions/7029993/differences-between-numpy-random-and-random-random-in-python).

The main takeaways are that:
- If you will be doing multi-threaded work and need replicable results, then you should use the built-in `random` module.
- The `numpy.random` module offers more/better/faster methods for generating groups of random numbers and from various distributions.
- Each module will use its own random-seed generator, so if you are using both in a project and want replicable results, then you will need to set the seed for each and separately.
- Neither module is random enough to use them for sensitive information, such as cryptography. For that, other modules are better alternatives such as `secrets` or `Crypto.Random` (for python pre v3.6).

To re-emphasize, the random numbers generated by `random` and by `numpy.random` are only 'pseudo' random. There are ways to generate more unpredictable random numbers, but that is not covered here.

### Generate Random Number

Use `random.randint()` imported from `numpy`.

In [17]:
from numpy import random
from configurations import printer, logger

logger.warning(
    'The current linter sensitivity flags usage of `randint` since it cannot\n'
    'infer its type. I have not found a way to modify the syntax to satisfy\n'
    'the linter. As a result, I deactivate the linter on those lines explicitly'
    )

my_rand_int_under_100 = random.randint(100) # type: ignore

printer('A random integer below 100 is:\n%s', my_rand_int_under_100)


2023-08-01 14:17:13 
	Logger: numpy-tutorial Module: 3362746361 Function: <module> File: 3362746361.py Line: 4
The current linter sensitivity flags usage of `randint` since it cannot
infer its type. I have not found a way to modify the syntax to satisfy
the linter. As a result, I deactivate the linter on those lines explicitly

A random integer below 100 is:
28
A random integer below 100 is:
28
A random integer below 100 is:
28


### Generate Random Float

Use `random.rand()` for floats.

In [19]:
from numpy import random
from configurations import printer

my_rand_float_under_100 = random.rand()

printer('A random float below 100 is:\n%s', my_rand_float_under_100)


2023-08-01 14:20:59 
	Logger: numpy-tutorial Module: 3133309597 Function: <module> File: 3133309597.py Line: 4
The current linter sensitivity flags usage of `randint` since it cannot
infer its type. I have not found a way to modify the syntax to satisfy
the linter. As a result, I deactivate the linter on those lines explicitly

A random float below 100 is:
0.28027469790326476


### Generate Random Array

For a 1D-array, both `random.randint()` and `random.rand()` can build an arry of the desired length by specifying either the `size` in `random.randint()` or the default first argument in `random.rand()`.

You can use the `size` argument  in the `random.randint()` method to specify a multi-dimensional array by sending it a tuple of dimension lengths.

In the `random.rand()` method, there is no need to wrap the dimension sizes in brackets to make it a tuple; it seems that the only arguments this method accepts are dimension sizes, so they will be interpreted as such directly.

In [24]:
from numpy import random
from configurations import printer, logger

logger.warning(
    'The current linter sensitivity flags usage of `randint` since it cannot\n'
    'infer its type. I have not found a way to modify the syntax to satisfy\n'
    'the linter. As a result, I deactivate the linter on those lines explicitly'
    )

my_array_of_10_ints = random.randint(100, size = 10) # type: ignore
my_array_of_10_floats = random.rand(10)

printer('An array of 10 ints under 100 is:\n%s', my_array_of_10_ints)
printer('An array of 10 floats is:\n%s', my_array_of_10_floats)

my_2D_array_of_10_ints = random.randint(100, size = (2, 5)) # type: ignore
printer('A 2D array of 10 ints under 100 is:\n%s', my_2D_array_of_10_ints)
my_3D_array_of_10_ints = random.randint(100, size = (2, 2, 2)) # type: ignore
printer('A 3D array of 8 ints under 100 is:\n%s', my_3D_array_of_10_ints)

my_2D_array_of_10_floats = random.rand(2, 5)
printer('A 2D array of 10 floats under 100 is:\n%s', my_2D_array_of_10_floats)
my_3D_array_of_10_floats = random.rand(2, 2, 2)
printer('A 3D array of 8 floats under 100 is:\n%s', my_3D_array_of_10_floats)


2023-08-01 14:33:08 
	Logger: numpy-tutorial Module: 27791156 Function: <module> File: 27791156.py Line: 4
The current linter sensitivity flags usage of `randint` since it cannot
infer its type. I have not found a way to modify the syntax to satisfy
the linter. As a result, I deactivate the linter on those lines explicitly

An array of 10 ints under 100 is:
[ 0 31 98 98 16 77 72  9 93 13]
An array of 10 floats is:
[0.54706229 0.40979491 0.00275936 0.13803244 0.94390318 0.82644164
 0.45027965 0.48952867 0.65726488 0.44473011]
A 2D array of 10 ints under 100 is:
[[49 71 40  8  3]
 [39 60 93 56 23]]
A 3D array of 8 ints under 100 is:
[[[31 24]
  [ 3 89]]

 [[40 41]
  [91 11]]]
A 2D array of 10 floats under 100 is:
[[0.56660531 0.60954453 0.52002741 0.10616489 0.62092369]
 [0.06445594 0.19075364 0.26865334 0.64454722 0.84639563]]
A 3D array of 8 floats under 100 is:
[[[0.31156014 0.39751807]
  [0.87301186 0.34763105]]

 [[0.35319668 0.70817876]
  [0.1629535  0.47556873]]]


### Generate Random Number From Array

If you have an array, you can use the `random.choice()` method to select one of them at random. You can specify the `size` argument to select multiple values from the array. Similar to using `size` when generating random arrays, you can send a tuple in order to get a multi-dimensional array.

By default, the `random.choice()` function does random selection with replacement, so you can even specify a return that has more values than the original array.

In [3]:
import numpy as np
from configurations import printer

array = np.array([*range(1, 11)])
printer('A random number between 1 and 10 is:\n%s', np.random.choice(array))
printer(
    '2 random numbers between 1 and 10 are:\n%s',
    np.random.choice(array, size=2))

printer(
    '12 random numbers between 1 and 10 arranged in a 3D array are:\n%s',
    np.random.choice(array, size=(2, 2, 3)))

A random number between 1 and 10 is:
3
2 random numbers between 1 and 10 are:
[9 5]
12 random numbers between 1 and 10 arranged in a 3D array are:
[[[10  4  5]
  [ 7  8  4]]

 [[ 6  2  1]
  [ 3  7  5]]]
