# NumPy Tutorial

https://www.w3schools.com/python/numpy/

## Random Permutation

A permutation means to shuffle the order of data in an array.

This can be done with `random.shuffle()` to shuffle an array in place, or with `random.permutation()` to return a new array.

In [1]:
import numpy as np
from configurations import printer

my_array = np.array([*range(1, 11)])

printer('My array is:\n%s', my_array)

my_permuted_array = np.random.permutation(my_array)

printer('My permuted array is:\n%s', my_permuted_array)
printer('My array is:\n%s', my_array)

printer('Shuffling my array')

np.random.shuffle(my_array)

printer('My permuted array is:\n%s', my_permuted_array)
printer('My array is:\n%s', my_array)

My array is:
[ 1  2  3  4  5  6  7  8  9 10]
My permuted array is:
[ 4  9  7  8  1 10  5  6  3  2]
My array is:
[ 1  2  3  4  5  6  7  8  9 10]
Shuffling my array
My permuted array is:
[ 4  9  7  8  1 10  5  6  3  2]
My array is:
[10  8  1  7  5  2  6  9  4  3]
